"""vediamo

Revision ID: 054895e246fa
Revises: 6b3b557a9f44
Create Date: 2022-04-05 13:11:22.472160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054895e246fa'
down_revision = '6b3b557a9f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gare', schema=None) as batch_op:
        batch_op.drop_column('immagine')

    with op.batch_alter_table('rioni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('immagine', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rioni', schema=None) as batch_op:
        batch_op.drop_column('immagine')

    with op.batch_alter_table('gare', schema=None) as batch_op:
        batch_op.add_column(sa.Column('immagine', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
