"""retifica

Revision ID: 6a6816521693
Revises: e25fa04e3a9e
Create Date: 2022-03-15 13:26:44.162706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6816521693'
down_revision = 'e25fa04e3a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gare', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rioni_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('primo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('secondo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('terzo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quarto', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quinto', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'rioni', ['rioni_id'], ['id'])
        batch_op.drop_column('rione_id')
        batch_op.drop_column('numero_corsa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gare', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_corsa', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rione_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'rioni', ['rione_id'], ['id'])
        batch_op.drop_column('quinto')
        batch_op.drop_column('quarto')
        batch_op.drop_column('terzo')
        batch_op.drop_column('secondo')
        batch_op.drop_column('primo')
        batch_op.drop_column('rioni_id')

    # ### end Alembic commands ###
