"""test

Revision ID: b6a67a9908c3
Revises: 
Create Date: 2022-03-18 18:50:40.509558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a67a9908c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rione', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('primo', sa.Integer(), nullable=True),
    sa.Column('secondo', sa.Integer(), nullable=True),
    sa.Column('terzo', sa.Integer(), nullable=True),
    sa.Column('quarto', sa.Integer(), nullable=True),
    sa.Column('quinto', sa.Integer(), nullable=True),
    sa.Column('valido', sa.Boolean(), nullable=False),
    sa.Column('rioni_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rioni_id'], ['rioni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('gare')
    op.drop_table('user')
    op.drop_table('rioni')
    # ### end Alembic commands ###
