"""upgrade rioni e corse

Revision ID: c7c6525f1373
Revises: 2cd752910026
Create Date: 2022-02-14 13:18:04.959258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c6525f1373'
down_revision = '2cd752910026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rione', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('numero_corsa', sa.Integer(), nullable=False),
    sa.Column('rione_id', sa.Integer(), nullable=False),
    sa.Column('valido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rione_id'], ['rioni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gare')
    op.drop_table('rioni')
    # ### end Alembic commands ###
