"""empty message

Revision ID: e25fa04e3a9e
Revises: 03b15f0f9fec
Create Date: 2022-02-24 18:58:49.696342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25fa04e3a9e'
down_revision = '03b15f0f9fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gare', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rione_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gare', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rione_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'rioni', ['rione_id'], ['id'])

    # ### end Alembic commands ###
